use_sim_time: true

# basic program type
# refer to src/legged_ctrl/include/LeggedState.h
run_type: 0
robot_type: 0
mpc_type: 0
low_level_type: 0

kp_foot_x: 50
kp_foot_y: 50
kp_foot_z: 50

kd_foot_x: 1.2
kd_foot_y: 1.2
kd_foot_z: 1.2

km_foot_x: 0.2
km_foot_y: 0.2
km_foot_z: 0.2


# joystick mapping ( must change according to your joystick)
joystick_left_updown_axis:   1
joystick_left_horiz_axis:    0
joystick_right_updown_axis:  4
joystick_right_horiz_axis:   3
joystick_mode_switch_button: 0
joystick_exit_button:        4


# joystick parameters
joystick_velx_scale:  2.5   # m/s
joystick_vely_scale:  0.4   # m/s
joystick_height_vel:  0.1   # m/s
joystick_max_height:  0.30  # m
joystick_min_height:  0.03  # m
joystick_yaw_rate_scale:   0.8  # rad/s
joystick_roll_rate_scale:  0.4  # rad/s
joystick_pitch_rate_scale: 0.4  # rad/s

# contact detection related 
foot_sensor_max_value: 300.0
foot_sensor_min_value:   0.0
foot_sensor_ratio:       0.5
