use_sim_time: true

# basic program type
# refer to src/legged_ctrl/include/LeggedState.h
run_type: 0
robot_type: 0
mpc_type: 0
low_level_type: 0

kf_type: 1        # 0: no kf ( only available in Gazebo)
                  # 1: linear KF
                  # 2: EKF
                  
kp_foot_x: 50
kp_foot_y: 50
kp_foot_z: 50

kd_foot_x: 1.2
kd_foot_y: 1.2
kd_foot_z: 1.2

km_foot_x: 0.2
km_foot_y: 0.2
km_foot_z: 0.2


# joystick mapping ( must change according to your joystick)
# for example, 
# - xbox controller has right updown axis as 4, right horizontal axis as 3
# - nvidia controller has right updown axis as 5, right horizontal axis as 2
joystick_left_updown_axis:   1
joystick_left_horiz_axis:    0
joystick_right_updown_axis:  4
joystick_right_horiz_axis:   3
joystick_mode_switch_button: 0
joystick_exit_button:        4


# joystick parameters
joystick_velx_scale:  2.5   # m/s
joystick_vely_scale:  0.4   # m/s
joystick_height_vel:  0.1   # m/s
joystick_max_height:  0.30  # m
joystick_min_height:  0.03  # m
joystick_yaw_rate_scale:   0.8  # rad/s
joystick_roll_rate_scale:  0.4  # rad/s
joystick_pitch_rate_scale: 0.4  # rad/s

# contact detection related 
# the range of sensor of A1 and Go1 are pretty different
foot_sensor_max_value: 200.0
foot_sensor_min_value:   0.0
foot_sensor_ratio:       0.5

# casadi EKF parameters
ekf_inital_cov:               0.01  
ekf_noise_process_pos_xy:     0.01
ekf_noise_process_pos_z:      0.01
ekf_noise_process_vel_xy:     0.01
ekf_noise_process_vel_z:      0.01
ekf_noise_process_rot:        0.000001
ekf_noise_process_foot:       0.01

ekf_noise_measure_fk:         0.001
ekf_noise_measure_vel:        0.001
ekf_noise_measure_height:     0.0001

ekf_noise_opti_pos:           0.001
ekf_noise_opti_vel:           999.0
ekf_noise_opti_yaw:           0.01

# robot parameters
a1_robot_mass: 13.0

a1_trunk_inertia_xx: 0.0158533
a1_trunk_inertia_xy: 0.0
a1_trunk_inertia_xz: 0.0
a1_trunk_inertia_yz: 0.0
a1_trunk_inertia_yy: 0.0377999
a1_trunk_inertia_zz: 0.0456542