use_sim_time: false

# basic program type
# refer to src/legged_ctrl/include/LeggedState.h
run_type: 1
robot_type: 0     # 0: A1
                  # 1: Go1
mpc_type: 1       # 0: CI-MPC
                  # 1: convex MPC 
                  # 2: ocs2 nonlinear MPC
low_level_type: 0 # 0: basic tau ctrl
                  # 1: whole body control 

# default foothold position in robot body frame (varialbes with "_rel" in the code)
default_foot_pos_FL_x: 0.20
default_foot_pos_FL_y: 0.13
default_foot_pos_FL_z: -0.3

default_foot_pos_FR_x: 0.20
default_foot_pos_FR_y: -0.13
default_foot_pos_FR_z: -0.3

default_foot_pos_RL_x: -0.19
default_foot_pos_RL_y: 0.13
default_foot_pos_RL_z: -0.3

default_foot_pos_RR_x: -0.19
default_foot_pos_RR_y: -0.13
default_foot_pos_RR_z: -0.3

# gait speed in phase per second
gait_counter_speed: 2.2    # 3 gait cycle per second

# convex MPC parameters

q_weights_0:  60.0 # roll
q_weights_1:  200.0 # pitch
q_weights_2:  0.0 # yaw

q_weights_3:  0.0 # pos x
q_weights_4:  0.0 # pos y
q_weights_5:  700.0 # pos z

q_weights_6:  0.1 # omega x
q_weights_7:  0.1 # omega y
q_weights_8:  100.0 # omega z

q_weights_9:  1.0 # vel x
q_weights_10: 1.0  # vel y
q_weights_11: 10.0 # vel z

q_weights_12: 0.0

r_weights_0:  0.0001
r_weights_1:  0.0001
r_weights_2:  0.0001

r_weights_3:  0.0001
r_weights_4:  0.0001
r_weights_5:  0.0001

r_weights_6:  0.0001
r_weights_7:  0.0001
r_weights_8:  0.0001

r_weights_9:  0.0001
r_weights_10: 0.0001
r_weights_11: 0.0001

# swing leg parameters
kp_foot_x: 25
kp_foot_y: 25
kp_foot_z: 25

kd_foot_x: 0.08
kd_foot_y: 0.08
kd_foot_z: 0.08

km_foot_x: 0.1
km_foot_y: 0.1
km_foot_z: 0.1





# joystick mapping ( must change according to your joystick)
# for example, 
# - xbox controller has right updown axis as 4, right horizontal axis as 3
# - nvidia controller has right updown axis as 5, right horizontal axis as 2
joystick_left_updown_axis:   1
joystick_left_horiz_axis:    0
joystick_right_updown_axis:  4
joystick_right_horiz_axis:   3
joystick_mode_switch_button: 0
joystick_exit_button:        4


# joystick parameters
joystick_velx_scale:  1.5   # m/s
joystick_vely_scale:  0.4   # m/s
joystick_height_vel:  0.1   # m/s
joystick_max_height:  0.30  # m
joystick_min_height:  0.03  # m
joystick_yaw_rate_scale:   0.8  # rad/s
joystick_roll_rate_scale:  0.4  # rad/s
joystick_pitch_rate_scale: 0.4  # rad/s

# contact detection related 
# the range of sensor of A1 and Go1 are pretty different
foot_sensor_max_value:   50.0
foot_sensor_min_value:   0.0
foot_sensor_ratio:       0.5

# casadi EKF parameters
ekf_inital_cov:               0.01  
ekf_noise_process_pos_xy:     0.01
ekf_noise_process_pos_z:      0.01
ekf_noise_process_vel_xy:     0.01
ekf_noise_process_vel_z:      0.01
ekf_noise_process_rot:        0.000001
ekf_noise_process_foot:       0.01

ekf_noise_measure_fk:         0.001
ekf_noise_measure_vel:        0.1
ekf_noise_measure_height:     0.0001

ekf_noise_opti_pos:           0.001
ekf_noise_opti_vel:           999.0
ekf_noise_opti_yaw:           0.01

# robot parameters
a1_robot_mass: 13.0

a1_trunk_inertia_xx: 0.0158533
a1_trunk_inertia_xy: 0.0
a1_trunk_inertia_xz: 0.0
a1_trunk_inertia_yz: 0.0
a1_trunk_inertia_yy: 0.0377999
a1_trunk_inertia_zz: 0.0456542